name: kicad
env:
  PUSH_NAME: 'John Stenger'
  PUSH_USER: 'rootnegativ1'
  PUSH_MESSAGE: 'Kicad Action'
on:
  push:
    branches: main
    paths:
      - '*.kicad_sch'
      - '*.kicad_pcb'
      - '.github/workflows/kibot_action_quick_start.yml'
  pull_request:
    paths:
      - '*.kicad_sch'
      - '*.kicad_pcb'
      - '.github/workflows/kibot_action_quick_start.yml'
  workflow_dispatch:

jobs:
  kicad:
    runs-on: ubuntu-latest
    steps:
    - name: Get Repo
      uses: actions/checkout@v3

    - name: Run KiBot
      uses: INTI-CMNB/KiBot@v2_k6
      with:
        config: config.kibot.yml
        dir: output
        schema: '*.kicad_sch'
        board: '*.kicad_pcb'

    - name: Push Changes
      run: |
        git config --global user.name "$PUSH_NAME"
        git config --global user.email "$PUSH_USER@users.noreply.github.com"
        git add output/*
        git commit -m "$PUSH_MESSAGE"
        git push
