name: kicad

on:
  push:
    branches: main
    paths:
      - 'v1.2/*.kicad_sch'
      - 'v1.2/*.kicad_pcb'
      - '*.kibot.yaml'
      - '.github/workflows/kicad.yaml'
  pull_request:
    paths:
      - 'v1.2/*.kicad_sch'
      - 'v1.2/*.kicad_pcb'
      - '*.kibot.yaml'
      - '.github/workflows/kicad.yaml'
  workflow_dispatch:

env:
  #BaseFileName: ${{ github.event.repository.name }}
  BaseFileName: 'alarm_panel'

jobs:
  kicad:
    runs-on: ubuntu-latest
    steps:
    - name: Get repo
      uses: actions/checkout@v3

    - name: Run KiBot
      uses: INTI-CMNB/KiBot@v2_k6
      with:
        config: config.kibot.yaml
        dir: output
        schema: v1.2/${{ env.BaseFileName }}.kicad_sch
        board: v1.2/${{ env.BaseFileName }}.kicad_pcb

    - name: Upload results
      uses: actions/upload-artifact@v3
      with:
        name: output
        #path: output/*
        path: |
          output/*.zip
          output/*.pdf
          output/*.step
          output/*.png

    - uses: actions/download-artifact@v3
      id: download
      with:
        name: output
        # path: output/*

    - name: 'Echo download path'
      run: echo ${{steps.download.outputs.download-path}}
  
    - name: Display structure of downloaded files
      run: ls -R
