name: kicad

on:
  push:
    branches: main
    paths:
      - 'main-board/**/*.kicad_sch'
      - 'main-board/**/*.kicad_pcb'
      - '*.kibot.yaml'
      # - '.github/workflows/kicad.yaml'
  pull_request:
    paths:
      - 'main-board/**/*.kicad_sch'
      - 'main-board/**/*.kicad_pcb'
      - '*.kibot.yaml'
      # - '.github/workflows/kicad.yaml'
  workflow_dispatch:

env:
  #BaseFileName: ${{ github.event.repository.name }}
  BaseFileName: 'alarm_panel'
  PUSH_MESSAGE: 'Kicad Action'

jobs:
  kicad:
    runs-on: ubuntu-latest
    steps:

    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: |
        echo "$GITHUB_CONTEXT"

    - name: Get repo
      uses: actions/checkout@v3

    - name: Run KiBot
      uses: INTI-CMNB/KiBot@v2_k6
      with:
        config: config.kibot.yaml
        dir: output
        schema: v1.2/${{ env.BaseFileName }}.kicad_sch
        board: v1.2/${{ env.BaseFileName }}.kicad_pcb

    # - name: Upload results
      # uses: actions/upload-artifact@v3
      # with:
        # name: output
        # path: |
          # output/*.zip
          # output/*.pdf
          # output/*.step
          # output/*.png
          # output/*.svg
          # output/*.csv

    # - uses: actions/download-artifact@v3
      # id: download
      # with:
        # name: output

    # - name: 'Echo download path'
      # run: echo ${{steps.download.outputs.download-path}}
  
    # - name: Display structure of downloaded files
      # run: ls -R

    # - name: Push files
      # run: |
        # git config --global user.name "$PUSH_NAME"
        # git config --global user.email "$PUSH_USER@users.noreply.github.com"
        # git add output/*
        # git commit -m "$PUSH_MESSAGE"
        # git push

    - name: Commit files
      id: commit
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "github-actions"
        git add output/*
        git commit -m "$PUSH_MESSAGE"

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
         github_token: ${{ secrets.GITHUB_TOKEN }}
