name: kicad

on:
  push:
    branches: main
    paths:
      - '*.kicad_sch'
      - '*.kicad_pcb'
      - '*.kibot.yaml'
      - '.github/workflows/kicad.yaml'
  pull_request:
    paths:
      - '*.kicad_sch'
      - '*.kicad_pcb'
      - '*.kibot.yaml'
      - '.github/workflows/kicad.yaml'
  workflow_dispatch:

jobs:
  kicad:
    runs-on: ubuntu-latest
    steps:
    - name: Get repo
      uses: actions/checkout@v3

    - name: Run KiBot
      uses: INTI-CMNB/KiBot@v2_k6
      with:
        config: config.kibot.yaml
        dir: output
        schema: 'alarm_panel_v1.1c.kicad_sch'
        board: 'alarm_panel_v1.1c.kicad_pcb'

    - name: Download results to current working directory
      uses: actions/download-artifact@v3
  
    - name: Display structure of downloaded files
      run: ls -R
